version: '3.9'

services:
  dedicated-server:
    image: kagurazakanyaa/palworld:latest
    build:
      context: .
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8211:8211
    environment:
      - GAME_PORT=8211
      - MAX_PLAYERS=32
      - ENABLE_MULTITHREAD=true
      - IS_PUBLIC=false
      - PUBLIC_IP=
      - PUBLIC_PORT=
      - FORCE_UPDATE=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/opt/palworld/Pal/Saved